version: '3.7'

services:
  environment:
    container_name: environment
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: node app.js
